version: '3.1'

services:
  mongo:
    image: mongo:4.4
    command: --nojournal
    volumes:
      - ./mongo:/data/db

  orion:
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo